SELECT * FROM PERSONS;

SELECT COUNTRY, STATE, COUNT(STATE) AS TOTAL_PERSONS, MIN(AGE) AS MIN_AGE
FROM PERSONS
GROUP BY COUNTRY, STATE
ORDER BY COUNTRY ASC;



SHOW TABLES;

SELECT * FROM CUSTOMERS
HAVING AVG(CUSTOMER_ID) > 2;